### ISSUE TITLE
Create registry file without local copies of the files

### ISSUE THREAD

**Issue by santisoler** [fatiando/pooch#130]
**Description of the desired feature**

When trying to fetch a large number of data files from a website, it's generally faster to download them programatically rather than doing it manually. Pooch seems a nice tool to make this process easier without having to write code for download, store and/or decompress the data before it can be loaded as we desire. Nevertheless, we need to have the hashes for the wanted files before Pooch being able to download them programatically, what can be a problem if we don't actually have local copies of those files. So, the solution so far is to write a script to download the files,  run `pooch.make_registry()` in order to compute the hashes and create the registry file. After these steps Pooch is ready to be used for fetching any file we want.

Would be nice if we can spare ourselves from writing the downloader script and allow Pooch to manage the entire process by simply passing the files we would like to fetch and the base url from which they can be downloaded. This feature would not be intended for the normal usage of Pooch, but  for one time only: when we need to download the files in order to compute the hashes and create the registry file.

I'm thinking we could write a function that gets a `pooch.Pooch` instance without a `registry`, a list of the files that wants to be downloaded and the path where the registry file will be saved. It should download every file in the list from the `base_url`, compute the hashes and then creating the registry.
Maybe it can be a method of `pooch.Pooch` class instead of an independent function.

Any idea or comment is welcome.

**Are you willing to help implement and maintain this feature?** Yes

**Comment by leouieda** [comment]
> I'm thinking we could write a function that gets a pooch.Pooch instance without a registry, a list of the files that wants to be downloaded and the path where the registry file will be saved. It should download every file in the list from the base_url, compute the hashes and then creating the registry.
Maybe it can be a method of pooch.Pooch class instead of an independent function.

The only thing such function needs to know if the URL, the list of files, and the output registry file. So something like `pooch.build_registry(url="http:....", files=["f1.csv", ...], output="datasets/registry.txt")` would do. It can use `HTTPDownloader` et al. No need for all the environment variables, versioning, etc, in `Pooch`. Files can be downloaded to temporaries and cleaned after. Optionally, it could take a `keep_data="data/"` argument which defaults to `None` to actually save the data files. 

To be fancy, the downloads could be parallelized with [`concurrent.futures.ProcessPoolExecutor`](https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.ProcessPoolExecutor) but I'm not sure it would make a huge difference since bandwidth is probably the limiting factor in speed.

**Comment by santisoler** [comment]
Yes, you're right, there's no need to pass a `Pooch` to build the registry.
We should think a good name for the new function.
I like the `keep_data` idea. In fact I would add a `check_hashes` argument. If `True`, the function will download the files, compute the hashes, create the registry and then download all files again and check if the hashes are correct. This would take twice the time, what could be problematic for large datasets, but it worth having an automated way to check if the hashes are correct and no downloaded file was corrupted. Maybe this option could be `False` by default.

**Comment by leouieda** [comment]
I like the double checking idea but it really should be off by default.

**Comment by santisoler** [comment]
We decided to add an example for performing this task rather than adding a specific function for that: https://github.com/fatiando/pooch/pull/161
