### ISSUE TITLE
Unused pooch argument on Downloaders.__call__ methods

### ISSUE THREAD

**Issue by santisoler** [fatiando/pooch#154]
**Description of the problem**

Both `HTTPDownloader` and `FTPDownloader` classes have a `__call__` method used for downloading the desire file through the corresponding protocol. The method ask for the url of the file, the output file where it should be saved to and a `pooch` argument.
According to the documentation, this `pooch` argument should be the `Pooch` instance that is calling the method, although it is not used inside it.
Is it an unused argument that should be removed or is there a reason for it?

**Comment by leouieda** [comment]
I initially put it there in case the callback needed some information about the `Pooch` object that is calling it. For example, it might need to know the `base_url` or the cache directory. The ones we have implemented don't use it but it's good to have the option. The processors have the same argument.

Removing it would require a deprecation first because it's part of the 1.0 API now.

**Comment by santisoler** [comment]
Thanks for the answer. I will close this issue then.
