### ISSUE TITLE
Convenience functions to list downloaded datasets, to delete them, and to show their location

### ISSUE THREAD

**Issue by MarkWieczorek** [fatiando/pooch#175]
Many datasets that will be downloaded by pooch will be very large and might only be used once by the user. It would be useful to have some convenience functions to list those datasets that have been downloaded, to delete all (or some) of them, to determine where they are stored, and to give the size of the downloaded files.

Convenience functions that one might want to add to a `datasets` module might include:

* `datasets_list()`
* `datasets_clear()`
* `datasets_path()`
* `datasets_size()`

Also, for the maintainer of a datasets module, it would be useful to have a simple function that would verify that all the datasets are indeed downloadable (i.e., the file exists). Oftentimes, files get moved around on a server over 5 year time spans.

**Comment by leouieda** [comment]
@MarkWieczorek that is a good list of things to implement :+1: 

> it would be useful to have a simple function that would verify that all the datasets are indeed downloadable

That can already be done with `pooch.Pooch.is_available` (thanks to @santisoler for insisting on this feature :-). So you could do `all(POOCH.is_available(fname) for fname in POOCH.registry)`.

> It would be useful to have some convenience functions to list those datasets that have been downloaded, ... and to give the size of the downloaded files.

I like the idea of listing downloaded files and their sizes. We could add something like a `Pooch.local_content` property that produces a dictionary of file names and their sizes (in bytes) in the local storage folder. I would keep the file names to match entries in the registry instead of providing the full path (appending to `Pooch.abspath`). This way, we can query `fname in POOCH.local_content` for example. This would solve the 2 use cases.

One caveat here is that this would not be able to account to decompressed/unzipped files since it would not have access to the particular processor used in `fetch`. An alternative approach that might be able to account for this is to capture the file size in `fetch` instead of generating it dynamically. That way, we can have the processor record the file sizes of the unpacked files using the `pooch` variable somehow. The trade-off here is that we then have to keep this information updated when new files are downloaded or deleted. Of course, we have no control if the user deletes files themselves. So we'd have to check that files are still present on start up. So I'm not too keen on this implementation since it will create a lot of problems and will be a nightmare to test.

A compromise could be to add an `"extra"` element to `Pooch.local_content` with a dictionary of file/folder names not in the registry and their sizes.

>  to delete all (or some) of them, 

Deleting select files will also get a bit tricky and I'm not sure there is a large enough use case for this to warrant the trouble it would be to implement and test (I can see this causing headaches on Windows, for example).

But it would be nice to have `Pooch.clear_cache` to delete all files from the cache. Not sure how much work this would save for users but it's a lot easier to instruct people to run this instead of telling them where to find all the files. One option that could be included is to only remove files greater than a size threshold. 

> to determine where they are stored, 

Already accessible though `Pooch.abspath`.

Is this what you had in mind @MarkWieczorek? Curious to know what others think.

**Comment by MarkWieczorek** [comment]
That seems reasonable to me. Here are a couple quick comments.

* I think that the biggest use case will be simply clearing the entire cache, so a clear_cache() function would be useful.
* I tried `pooch.Pooch.abspath` but this returned `<property at 0x11435f8f0>`. Would it be possible to return a string?
* It might be useful to add a convenience function to delete a downloaded file (or the last downloaded file). The use case would be loading a dataset: First you download it, you process is into what ever you are going to return to the user, then you delete the file. I know that this could be done using low level functions if you wanted to. A lot of times, people just want to peek at the data to see if it is worth using later. Perhaps in this case you could instead save the file in some kind of system folder that is automatically cleared at the end of the session.

**Comment by leouieda** [comment]
> I tried pooch.Pooch.abspath but this returned <property at 0x11435f8f0>. Would it be possible to return a string?

`abspath` is a property so you should be able to do `open(POOCH.abspath / "myfile.txt")` but if you need a string representation instead of `pathlib.Path`  (some things don't work with them in 3.5) you can use `str(POOCH.abspath)`.

> I think that the biggest use case will be simply clearing the entire cache, so a clear_cache() function would be useful.

:+1: see #181 

> It might be useful to add a convenience function to delete a downloaded file (or the last downloaded file). The use case would be loading a dataset: First you download it, you process is into what ever you are going to return to the user, then you delete the file. I know that this could be done using low level functions if you wanted to. A lot of times, people just want to peek at the data to see if it is worth using later. Perhaps in this case you could instead save the file in some kind of system folder that is automatically cleared at the end of the session.

Right, I hadn't thought of that use case. But most times users wouldn't be touching Pooch directly, right? In this use case, I imagine the user would be directly calling something like `pooch.retrieve`? In that case, we don't store the location of the data (since it's user configurable when calling the function). So there would be no way to delete it after the fact.

Or do you envision used the delete functionality inside a package function?

**Comment by MarkWieczorek** [comment]
Forget the last part: We can just use `os.remove(fname)`. I mistakenly thought that pooch was saving other metafiles as well, with things like hashes.

**Comment by leouieda** [comment]
Well, if using `Decompress` or `Unzip/Untar` then there will be other files associated with the data file that need to be cleaned. So it might be good to have pooch remove things. I was just trying to imagine how an end user would see this instead of a package developer.

**Comment by leouieda** [comment]
Closing this as it seems that main use case is clearing the cache which is now in #181
