### ISSUE TITLE
Handle hash capitalization

### ISSUE THREAD

**Issue by jrleeman** [fatiando/pooch#193]
Windows users will likely hit an issue when making a data manifest file as most guidance online shows finding the SHA256 of a file in power shell like this:

```
Get-FileHash myfile.bin | Format-List
```

Which then produces output like

```
Algorithm : SHA256
Hash      : 7268E3A01D57CCE828BCB7E0FF82F9048AB3A70520C58516A1145B51F7032A1D
Path      : C:\Users\myuser\myfile.bin
```

If that hash is pasted right into the manifest file pooch will try to update the file as the caps in the hash don't match strictly. I don't *believe* there would be any follow on consequences of running info read from the manifest through `.lower()` before checking for a hash match?

**Comment by leouieda** [comment]
It should be fine since the hexadecimal representation of the hash should be case insensitive. Would be good to add a test for this, though. Better than adding `.lower()` when reading the hash from a file would be to add it when comparing hashes. That would allow upper case hashes anywhere. It would only be a matter of adding that to this line: https://github.com/fatiando/pooch/blob/master/pooch/utils.py#L371

The test could add an entry with an upper case hash and check that everything still works as expected. To be extra thorough, an upper case entry in the text file and in the Python code (in `pooch/tests/utils.py`) would be nice to have.

**Comment by jrleeman** [comment]
Hmm - I can verify that on Win10 it was not fine. Test will be interesting then for sure!

**Comment by leouieda** [comment]
Maybe not a good first issue then 🙂 What exactly went wrong? Do you think lowering both the stored and computed hashes would work?
