### ISSUE TITLE
pooch.create should test for write access to directories and have a failback for failures

### ISSUE THREAD

**Issue by akrherz** [fatiando/pooch#22]
See realworld implementation problem with Unidata/MetPy#933

`pooch.create` can fail to write to whatever cache directory it is presented with.  A failback mechanism should exist, like what does with `matplotlib` when it attempts to find writable locations.  There is also a [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) for this. 

```python
POOCH = pooch.create(
    path=pooch.os_cache('metpy'),
    base_url='https://github.com/Unidata/MetPy/raw/{version}/staticdata/',
    version='v' + __version__,
    version_dev='master',
    env='TEST_DATA_DIR')
```

## Full error message

```
File "/opt/miniconda3/envs/prod/lib/python3.6/site-packages/pooch/core.py", line 143, in create
   os.makedirs(versioned_path)
 File "/opt/miniconda3/envs/prod/lib/python3.6/os.py", line 210, in makedirs
     makedirs(head, mode, exist_ok)
  File "/opt/miniconda3/envs/prod/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/opt/miniconda3/envs/prod/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/share/httpd/.cache'
```

thank you

**Comment by leouieda** [comment]
Hi @akrherz thanks for reporting!

A way to implement this would be to allow `pooch.create` to take a list of directories and try writing a temp file to them in order. The first one that passes will be the data dir. This could be made transparent to Metpy and others by having `os_cache` return a list of default directories instead of just a single one.

What do you think?

**Comment by akrherz** [comment]
Thanks @leouieda I really like how `matplotlib` handles this.  Their code is barried though in their `__init__.py` so can't just call it easily.  I like your idea on `os_cache()`, but I could not design an API to save my life.

**Comment by leouieda** [comment]
Yeah, I always have a hard time tracking down the matplotlib code. It's so convoluted sometimes.

One issue we have with this is that `create` already [takes a list as the `path`](https://github.com/fatiando/pooch/blob/master/pooch/core.py#L34) but it joins them automatically. This was to spare the user from having to import `os.path` but now it comes back to bite us (designing APIs is **hard**). Since we only have 2 users right now, I don't it would be bad to break this. 

I think these changes to the API would solve this problem:

* `os_cache` returns a list of directories. We still need to determine what this list should be but something like `[default cache dir, user dir]`. 
* `create` will not be able to join paths anymore.
* `create` can take a list of directories and test each one in order.

But now that I think about, in your example the user directory is `/usr/share/httpd` for some reason. So no matter what we chose in `os_cache`, we wouldn't have permission to write to it. So we should probably add a `try: .. except:` block to add a message telling the user to set the environment variable if `os.makedirs` fails. I don't if there is much else we can do.

cc @jrleeman @dopplershift

**Comment by jrleeman** [comment]
I'm thinking we just fail with a warning that cache operations are unavailable until the user sets the environment variable. Might not matter for some folks and sys admins will want a custom location anywho most likely.

**Comment by leouieda** [comment]
So we would still download the files but just never write them to the cache directory?

**Comment by jrleeman** [comment]
I agree @dopplershift. Create does create the directory, but that shouldn't kill this workflow.

**Comment by leouieda** [comment]
Right now, `create` tries to make the directory. We could offload that to `fetch` so that the package doesn't break on import.

**Comment by leouieda** [comment]
That would be a good thing actually. We don't want things breaking on import. Having a better error message would also be good.

**Comment by leouieda** [comment]
OK, #23 should solve this:

* Not fail on import. `create` tries to create the folder (or a temp file if it already exists) and warns of permission errors, including instructions for setting the appropriate env variable.
* `fetch` will fail if trying to create or write to the folder.

Just waiting on a pytest bug fix.
