### ISSUE TITLE
Read from URL into memory without downloading

### ISSUE THREAD

**Issue by lgloege** [fatiando/pooch#233]
Maybe this is beyond the scope of the package, but it would be great to read data into memory without storing it locally. 

I am not sure if this is even useful to the community, but here is a small working example of how to read a NetCDF file from a server into memory. 

```python
import urllib.request
import xarray as xr
import io

url = 'ftp://ftp2.psl.noaa.gov/Datasets/ncep.reanalysis2.dailyavgs/gaussian_grid/air.2m.gauss.1979.nc'

req = urllib.request.Request(url)

with urllib.request.urlopen(req) as resp:
    ds = xr.open_dataset(io.BytesIO(resp.read()))
```

You can also read from zip files. Sometimes you have to trick the server into thinking you a web browser, that is what the User-Agent is doing:

```python
import urllib.request
import xarray as xr
import zipfile
import io

url = 'https://www.metoffice.gov.uk/hadobs/en4/data/en4-2-1/EN.4.2.1.analyses.g10.1913.zip'

headers = {'User-Agent':"Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.17 (KHTML, like Gecko) Chrome/24.0.1312.27 Safari/537.17"}
req = urllib.request.Request(url, headers=headers)

with urllib.request.urlopen(req) as resp:
    with zipfile.ZipFile(io.BytesIO(resp.read())) as zip_file:
        zip_names = zip_file.namelist()
        ds = xr.open_dataset(zip_file.open(zip_names[0]))
```

If this is something worthwhile to the community I am happy to help implement this feature with some guidance. I am new to creating custom python packages.

**Comment by leouieda** [comment]
@lgloege this is neat! I didn't know about `BytesIO`. It seems like this could work well for http downloads. One way to implement this would be to add an argument to `pooch.Pooch.fetch` and `pooch.retrieve` (like `return_bytes`) that would make the functions generate a `BytesIO` object instead of a file path. The `HTTPDownloader` already accepts file-like objects so this should work.

Of course, this would also mean bypassing the hash check but that should be fine if you're willing to read data directly from memory.

I'm curious if you have a particular use case for this or if it's a "nice to have" feature. If anyone else has a use case, then I'd consider adding but if not, then it might be best to leave this issue open until someone has a use case. It adds complexity and potential vulnerability to the code so I wouldn't want to maintain this unless people actually use it.

**Comment by lgloege** [comment]
Thanks @leouieda ! Giving  `pooch.Pooch.fetch` and `pooch.retrieve`  the ability to output `BytesIO` objects sounds like the best way to maintain everything. These objects can be passed to new helper depending on the file type. For example, a  `ZipDownloader` could be built for .zip files. 

I have two use cases in mind:

1.  Make analyses fully reproducble. For example, this can make the data pre-processing step fully reproducible without requiring someone on the other end to download the raw data first. 

2. Maintaining data products. For example, a group of us in oceanography work on gap-filling sparse ocean pCO2 data, which requires a suite of auxiliary datasets. These pCO2 products are updated annually and used in the annual Global Carbon Budget. The ability to read data directly into memory avoids having to download the latest input files each time the product is updated. 

Please let me know if there is anything I can do to help implement this.

**Comment by rabernat** [comment]
I just found this issue.

Within Pangeo we are working a lot on "cloud-native" style workflows that bypass downloading and go straight to reading data off a server. [fsspec](https://filesystem-spec.readthedocs.io/) is out go-to package for this, since it implements almost every known file transfer protocol.

With your original example it looks like this.

```python
import fsspec
import xarray as xr
url = 'ftp://ftp2.psl.noaa.gov/Datasets/ncep.reanalysis2.dailyavgs/gaussian_grid/air.2m.gauss.1979.nc'
with fsspec.open(url) as fp:
    ds = xr.open_dataset(fp)
    print(ds)
```

This works pretty well, modulo the challenges we have seeking within hdf5 files over HTTP. ([This blog post](https://medium.com/pangeo/fake-it-until-you-make-it-reading-goes-netcdf4-data-on-aws-s3-as-zarr-for-rapid-data-access-61e33f8fe685) explains that in more detail.)

But all of this begs the question: **why does Pooch need to be involved?** Pooch is explicitly for downloading files. If you don't want to download the files, why would you need Pooch at all?

**Comment by lgloege** [comment]
Thanks, @rabernat. I wasn't aware of fsspec, that is a really cool package! I agree fsspec and pooch solve two different problems so it is probably best to keep them separate. Thanks again for sharing

**Comment by leouieda** [comment]
@rabernat you're absolutely right about this. In hindsight, it should have been clearer that this is out of scope because it would require bypassing our main selling features (easy download and caching, checksum verification).

Closing this a it's not in scope and fsspec solves the problem better than we could. Thanks @lgloege for the initial suggestion and @rabernat for pointing out the better solution!
