### ISSUE TITLE
Offline testing

### ISSUE THREAD

**Issue by avalentino** [fatiando/pooch#247]
I'm currently working on the packaging of pooch for debian.

Currently the test suite produces several errors during the debian package build because of network unavailability.
At the moment, as a workaround, I disabled offending tests using the following pytest parameters:

```
--ignore pooch/tests/test_processors.py \
--ignore pooch/tests/test_integration.py \
-k "not test_ftp_downloader \
and not test_downloader_progressbar_ftp \
and not test_retrieve \
and not test_pooch_logging_level \
and not test_pooch_update \
and not test_pooch_corrupted \
and not test_pooch_custom_url \
and not test_pooch_download \
and not test_check_availability \
and not test_fetch_with_downloader \
and not test_stream_download \
and not test_downloader \
and not test_sftp_downloader"
```

Is there currently  a smarter way to achieve the same result? 

If not, my request is to add a custom pytest mark to all tests accessing the interned so that it is easier to deselect them in cases (like mine) when the internet is not available.

**Comment by leouieda** [comment]
Hi @avalentino thanks for the issues! We hadn't tested Pooch under these cases before so this is very useful.

Properly testing everything without a connection would requiring setting up a development server and since #241 this would require a lot of work. Personally, I don't have the time to work on this but if anyone is interested in giving it a shot I wouldn't mind reviewing such a PR.

For now, we can certainly mark tests that require internet access so it's easier for you to exclude them.
