### ISSUE TITLE
Local-only/strict mode

### ISSUE THREAD

**Issue by dopplershift** [fatiando/pooch#290]
The problem I'm trying to solve is that for a CI build, if the PR is changing a file but neglects to update the hash in the registry, the behavior is to silently (with default logging) re-download the file from the remote source. If there are no other tests depending on the datafile (😱) then the PR passes CI, but will fail future builds (because the committed registry and datafile are out of sync).

Would there be any interest in adding a flag to disable updating the file? My hack right now is to (on my CI builds) set `base_url` to something like `'NODOWNLOAD:'`. This is both simply just terrible and also results in errors complaining about the URL protocol rather than the true source: the bad hash.

I'd be happy to take a shot at implementing, if someone can point me to what the best approach is for this here.

**Comment by leouieda** [comment]
@dopplershift ouch! So the PR passes because it fetches the data from `main` to update the file, right? Even if tests depend on the data file, they still may pass if the changes to the data are small. 

Here is a way to implement this:

* Add an `allow_updates=True` argument to `Pooch` and `create`. 
* If `allow_updates=False`, raise an exception before doing the download in `Pooch.fetch` when `action == "update"`: https://github.com/fatiando/pooch/blob/main/pooch/core.py#L543

I would advise against setting `allow_updates=False` always and only do this on CI. Otherwise, people with cached data from the `main` branch will get errors instead of Pooch updating the data (this is what motivated the implementation on updating in the first place). So it would be great to set this with an environment variable as well. My proposal would be:

* In `create`, `allow_updates` can be a bool or a string with the environment variable name. If it's a string, then check if the variable is set and equals `"false"` and update `allow_updates` accordingly. Then pass along a bool when instantiating `Pooch`. This is how we handle the cache location as well so it would be consistent.

As for documentation, it could go at the end of https://www.fatiando.org/pooch/latest/sample-data.html as a recommendation for package developers to set on CI. 

What do you think?

**Comment by dopplershift** [comment]
Correct. It was a station table that had a bad location that someone caught and fixed. That station wasn't used by any of our tests (and adding a test that a particular station in a table of 6000 is correct seems wrong).

That seems like a good approach, and in full agreement that `allow_updates=True` should be the default and normal case. I just need the ability to tell Pooch that "any attempt to update a file is an error", which this would allow me to do on CI (and local runs out of git).

Thanks for the pointers on implementation, I'll knock out a quick PR.
