### ISSUE TITLE
Fetching data that requires a username + password

### ISSUE THREAD

**Issue by danshapero** [fatiando/pooch#65]
Some data sets, such as those hosted by the [Global Hydrology Resource Center](https://ghrc.nsstc.nasa.gov/home/) or the [National Snow and Ice Data Center](https://nsidc.org/), require a username and password for access. It would be really convenient if pooch had a way to ask the user for a password when the example data require it. The repo owner would probably have to specify something in the registry to let pooch know that authentication needs to happen.

The requests library includes support for [authentication](http://2.python-requests.org/en/master/user/authentication/), which should be useful. I can help implement this but I don't have a great idea of what the API should be.

**Comment by leouieda** [comment]
Hi @danshapero, I've been thinking about this a bit and doing some research. There are many different types of authentication and each website need a different type. So I don't think there is a generic solution that will work for everyone. 

For your use case, I found that this works:

```python
login = requests.get("https://n5eil01u.ecs.nsidc.org/ICEBRIDGE/IDBMG4.003/1993.01.01/BedMachineGreenland-2017-09-20.nc.xml")
response = requests.get(login.url, auth=("USERNAME", "PASSWORD"))
```

We need the 2 calls to `get` because the first one redirects to the actual login page where the username and password can be given. From [the comments on this stackoverflow question](https://stackoverflow.com/a/37990889/1259381) it seems like there is no way of doing it in one go. But this might not be the case for other websites.

In #59, we added a mechanism to pass in a "post-download hook" callback function to perform some actions on the file after it's been downloaded. This function hijacks the return argument of `Pooch.fetch`. An example use case is [unzipping a file after download and returning the name of unzipped file](https://www.fatiando.org/pooch/dev/usage.html#post-processing-hooks). This was added as a way to customize behavior without having to subclass `pooch.Pooch`.

So maybe we could add a "downloader" callback as well. This function would be called *instead* of the download code we currently have.

It could work like this:

The user code would be

```python
def download_with_auth(url, output_file, mypooch):
    username = os.environ.get("EARTHDATA_USERNAME", None)
    password = os.environ.get("EARTHDATA_PASSWORD", None)
    assert username is not None and password is not None
    login = requests.get(url)
    response = requests.get(login.url, auth=(username, password), stream=True)
    response.raise_for_status()
    with open(output_file, "wb") as fout:
        for chunk in response.iter_content(chunk_size=1024):
            if chunk:
                fout.write(chunk)

def fetch_mydata():
    fname = MYPOOCH.fetch("datafile.nc", downloader=download_with_auth)
    ...
```

Basically, a user can implement how they want the data to be downloaded. This would cover your use case and even others, like FTP downloads (which `requests` doesn't support).

Of course, we could implement some default downloaders like `HTTPDownloader` or `FTPDownloader` that cover the basic use cases so that users don't have to write so much code. Something like:


```python
def fetch_mydata():
    username = os.environ.get("EARTHDATA_USERNAME", None)
    password = os.environ.get("EARTHDATA_PASSWORD", None)
    assert username is not None and password is not None    
    fname = MYPOOCH.fetch("datafile.nc", downloader=pooch.HTTPDownloader(auth=(username, password)))
    ...
```

or in your case


```python
def download_with_auth(url, output_file, mypooch):
    username = os.environ.get("EARTHDATA_USERNAME", None)
    password = os.environ.get("EARTHDATA_PASSWORD", None)
    assert username is not None and password is not None
    login = requests.get(url)    
    downloader = pooch.HTTPDownloader(auth=(username, password))    
    downloader(login.url, output_file, mypooch)

def fetch_mydata():    
    fname = MYPOOCH.fetch("datafile.nc", downloader=download_with_auth)
    ...
```

This will require some refactoring of the Pooch internals but would also solve #27

@danshapero @fatiando/pooch what do you think?
