### ISSUE TITLE
Add progress bar for downloads

### ISSUE THREAD

**Issue by danshapero** [fatiando/pooch#91]
**Description of the desired feature**

Add a progress bar for downloads using, say, [tqdm](https://github.com/tqdm/tqdm) or [python-progressbar](https://github.com/WoLpH/python-progressbar).
Getting this level of feedback is nice especially if you're on a slow connection.

Currently pooch issues a warning when something is being downloaded.
This is useful feedback because the dataset will be only be downloaded the first time you fetch it.
If there's more than one way to provide feedback, some changes to the API might be necessary to specify which one.

**Are you willing to help implement and maintain this feature?** Yes

**Comment by leouieda** [comment]
Hi @danshapero thanks for opening the issue! It would be great to have tqdm support in our downloader. The change should be made to `HTTPDownloader`. Since this is not the current behavior, we should probably make it optional at first. If we want to make this the default, we can include a notice that it will be the default in a future release and a way to opt out so people can have time to adapt. Most projects use small test data so I imagine most people won't want this on by default.

One way to implement this would be to introduce a new `progressbar=False` argument for `HTTPDownloader` and add tqdm to the download loop if `True`. This way, the bar will be off by default and people can turn it on by passing `downloader=HTTPDownloader(progressbar=True)` to `Pooch.fetch`.

This is a good reference for how to implement this: https://stackoverflow.com/a/37573701/1259381

What do you think?

**Comment by danshapero** [comment]
Suits me, I've used tqdm before. Do you want to make it a hard dependency (add to setup.py and requirements.txt) or an optional one?

**Comment by leouieda** [comment]
It can be optional for now since the behavior is off by default.
